name: 11 - Let's Encrypt - Create Certificate

# Controls when the workflow will run
on:
  # manual trigger
  workflow_dispatch:

jobs:
  generate-certificate:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # step 1 Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # step 2 Install Certbot
      - name: Install Certbot
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install certbot certbot-dns-azure

      # step 3 Verify the certbot installation
      - name: Verify the certbot installation
        run: |
          certbot --version
          certbot plugins

      # step 4 Create the certbot configuration file
      - name: Create the certbot configuration file
        run: |
            echo "dns_azure_sp_client_id = \"$AZURE_CLIENT_ID\"" > certbot.ini
            echo "dns_azure_sp_client_secret = \"$AZURE_CLIENT_SECRET\"" >> certbot.ini
            echo "dns_azure_subscription_id = \"$AZURE_SUBSCRIPTION_ID\"" >> certbot.ini
            echo "dns_azure_tenant_id = \"$AZURE_TENANT_ID\"" >> certbot.ini
            echo "dns_azure_environment = \"AzurePublicCloud\"" >> certbot.ini
            dns_azure_zone1 = "$AZURE_DNS_ZONE:/subscriptions/$AZURE_SUBSCRIPTION_ID/resourceGroups/$AZURE_RESOURCE_GROUP"

      # step 5 Show the content of the certbot configuration file
      - name: Show the content of the certbot configuration file
        run: |
          cat certbot.ini


